In [19]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/car-price-prediction-dataset/cardekho.csv

In [20]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

In [21]:
df = pd.read_csv("/kaggle/input/car-price-prediction-dataset/cardekho.csv")
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                8128 non-null   object
 1   year                8128 non-null   int64
 2   selling_price       8128 non-null   int64
 3   km_driven           8128 non-null   int64
 4   fuel                8128 non-null   object
 5   seller_type         8128 non-null   object
 6   transmission        8128 non-null   object
 7   owner               8128 non-null   object
 8   mileage(km/ltr/kg)  7907 non-null   float64
 9   engine              7907 non-null   float64
 10  max_power           7913 non-null   object
 11  seats               7907 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 762.1+ KB

,year,selling_price,km_driven,mileage(km/ltr/kg),engine,seats
count,8128.000000,8.128000e+03,8.128000e+03,7907.000000,7907.000000,7907.000000
mean,2013.804011,6.382718e+05,6.981951e+04,19.418783,1458.625016,5.416719
std,4.044249,8.062534e+05,5.655055e+04,4.037145,503.916303,0.959588
min,1983.000000,2.999900e+04,1.000000e+00,0.000000,624.000000,2.000000
25%,2011.000000,2.549990e+05,3.500000e+04,16.780000,1197.000000,5.000000
50%,2015.000000,4.500000e+05,6.000000e+04,19.300000,1248.000000,5.000000
75%,2017.000000,6.750000e+05,9.800000e+04,22.320000,1582.000000,5.000000
max,2020.000000,1.000000e+07,2.360457e+06,42.000000,3604.000000,14.000000

In [22]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0

In [23]:
df.skew(numeric_only=True).sort_values(ascending=False)

km_driven             11.170910
selling_price          4.193533
seats                  1.969914
engine                 1.135269
mileage(km/ltr/kg)    -0.142667
year                  -1.072293
dtype: float64

In [24]:
def remove_outliers_iqr(data, cols):
    for col in cols:
        Q1 = data[col].quantile(0.25)
        Q3 = data[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        data = data[(data[col] >= lower) & (data[col] <= upper)]
    return data

numeric_cols = ["engine", "year", "selling_price", "km_driven", "mileage(km/ltr/kg)", "seats"]
df = remove_outliers_iqr(df, numeric_cols)

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater_equal
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less_equal
  return op(a, b)

In [25]:
right_skewed = ["km_driven", "engine", "seats", "selling_price"]
for col in right_skewed:
    df[col] = np.log1p(df[col])

In [26]:
cat_cols = df.select_dtypes(include="object").columns.tolist()
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
num_cols.remove("selling_price")

In [27]:
preprocess = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_cols),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols)
    ]
)

In [28]:
X = df.drop("selling_price", axis=1)
y = df["selling_price"]  # already log-transformed

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [29]:
rf_pipeline = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", RandomForestRegressor(
        n_estimators=300,
        random_state=42,
        n_jobs=-1
    ))
])

rf_pipeline.fit(X_train, y_train)
rf_pred = rf_pipeline.predict(X_test)

In [30]:
gb_pipeline = Pipeline(steps=[
    ("preprocess", preprocess),
    ("model", GradientBoostingRegressor(random_state=42))
])

gb_pipeline.fit(X_train, y_train)
gb_pred = gb_pipeline.predict(X_test)

In [31]:
rf_pred = np.expm1(rf_pred)
gb_pred = np.expm1(gb_pred)
y_test = np.expm1(y_test)

In [32]:
def evaluate(y_true, y_pred):
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    print("MAE:", mae)
    print("R2:", r2)

print("Random Forest:")
evaluate(y_test, rf_pred)

print("Gradient Boosting:")
evaluate(y_test, gb_pred)

Random Forest:
MAE: 47838.37142016096
R2: 0.9148242530043397
Gradient Boosting:
MAE: 67340.588341526
R2: 0.8482618280110884

In [34]:
rf_model = rf_pipeline.named_steps["model"]
importances = rf_model.feature_importances_

# Need to extract one-hot encoded columns
encoded_cols = rf_pipeline.named_steps["preprocess"].transformers_[1][1].get_feature_names_out(cat_cols)
all_cols = num_cols + list(encoded_cols)

importance_df = pd.DataFrame({
    "feature": all_cols,
    "importance": importances
}).sort_values("importance", ascending=False)

importance_df.head(20)

                     feature  importance
0                       year    0.597899
3                     engine    0.222920
2         mileage(km/ltr/kg)    0.031457
1                  km_driven    0.025610
1347            max_power_69    0.005265
1217     transmission_Manual    0.004947
1216  transmission_Automatic    0.004909
1218       owner_First Owner    0.003582
1367          max_power_79.4    0.003561
1348         max_power_69.01    0.002369
1312          max_power_53.5    0.002311
1220      owner_Second Owner    0.002268
1357            max_power_74    0.002175
1221       owner_Third Owner    0.002062
1349            max_power_70    0.001887
1338            max_power_67    0.001880
1265         max_power_126.2    0.001806
1210             fuel_Diesel    0.001795
1360            max_power_75    0.001491
1394          max_power_88.5    0.001351